{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.imagePullSecrets 0).name | default "aliyun-registry-secret" }}
  labels:
    {{- include "cybertron-portal.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "cybertron-portal.dockerconfigjson" . }}
{{- end }}
