{{- if .Values.ingress.enabled }}
{{- $fullName := include "cybertron-portal.fullname" . -}}
{{- $backendName := include "cybertron-portal.backend.fullname" . -}}
{{- $frontendName := include "cybertron-portal.frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cybertron-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if eq .service "backend" }}{{ $backendName }}{{ else }}{{ $frontendName }}{{ end }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
